### ISSUE TITLE
Not Work With Sounds, like landing,jumping or running sound

### ISSUE THREAD

**Issue by arashsh80s** [ta-david-yu/2D-Platformer-Hunter#3]

**Comment by ta-david-yu** [comment]
Those features are definitely achievable. 
You can register OnStateChanged and OnJump event, and play the sounds when these events are triggered. 
As for the running sound, you can simply add an animation event on your running animation clip.

**Comment by ta-david-yu** [comment]
![image](https://user-images.githubusercontent.com/8101387/86513001-ee945080-be06-11ea-8534-c7a37ac5aebd.png)
