### ISSUE TITLE
Motor Collider

### ISSUE THREAD

**Issue by ajmortell** [ta-david-yu/2D-Platformer-Hunter#4]
Not really an issue. The motor works pretty great. Is there any way to out-of-box access the collider that is around the player? I want to adjust it for ducking. I have an abstract class called Behavior and Duck is a behavior component. When my character ducks I need to access the center of the box and the collider itself to resize it. I will need to access the motion speed as well to stop him when he attacks and speed him up when running. Awesome addition to 2D controllers.

**Comment by ajmortell** [comment]
I also can't seem to find a way to set an animation when he is climbing.

**Comment by ta-david-yu** [comment]
> Not really an issue. The motor works pretty great. Is there any way to out-of-box access the collider that is around the player? I want to adjust it for ducking. I have an abstract class called Behavior and Duck is a behavior component. When my character ducks I need to access the center of the box and the collider itself to resize it. I will need to access the motion speed as well to stop him when he attacks and speed him up when running. Awesome addition to 2D controllers.

I plan to refactor most of the code into a more modular structure, so users will be able to add a new state on their own. 
For now, if you wanna change the size of the bounding box, you can access the collider and change the bounds directly and call Raycaster.CalculateRaySpacing() to update the rays position afterwards.

**Comment by ta-david-yu** [comment]
> I also can't seem to find a way to set an animation when he is climbing.

Not sure if you are talking about ladder-climbing or wall-climbing.
For ladder-climbing:
- You can register a callback to CharacterController.OnMotorStateChanged. The state of the motor is set to MotorState.OnLadder when you are climbing a ladder.
